language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
    - master

script:
  - yarn lint
  - yarn test --ci
